---
# yamllint disable rule:line-length
version: "3.6"

services:
    consul:
        container_name: "consul"
        image: "consul:latest"
        ports:
            - "8500:8500"
            - "8300:8300"
        volumes:
            - ./config:/config
            - ./_data/consul:/data
        command: "agent -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -ui"

    vault:
        container_name: "vault"
        image: "vault"
        links:
            - consul:consul
        depends_on:
            - consul
        ports:
            - "8200:8200"
            - "22:22"
        volumes:
            - ./config:/config
            - ./vault/venafi:/vault/venafi
        cap_add:
            - IPC_LOCK
        command: "server -config=/config/vault.hcl"

    mssql:
        container_name: "mssql"
        image: "mcr.microsoft.com/mssql/server"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Testing123
            - MSSQL_PID=Developer
        ports:
            - "1433:1433"
#
# ldap:
#   container_name: openldap
#   image: mwaeckerlin/openldap
#   ports:
#     - '389:389'
#     - '636:636'
#   environment:
#     - DOMAIN=fewknow.com
#     - ORGANIZATION=FEWKNOW
#     - PASSWORD=testing123
# lam:
#   container_name: lam
#   image: mwaeckerlin/lam
#   ports:
#     - '8080:80'
